# Generated by Django 5.0.6 on 2025-05-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Household', '0003_like_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastereport',
            name='collected_by',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
