# Generated by Django 5.2.1 on 2025-05-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Household', '0004_alter_wastereport_collected_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastereport',
            name='collected_by',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wastereport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
