# Generated by Django 5.0.6 on 2025-06-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Household', '0005_alter_wastereport_collected_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illegaldumping',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Under processing'), ('validated', 'Validated'), ('invalid', 'Invalid')], default='pending', max_length=20),
        ),
    ]
