# Generated by Django 5.0.6 on 2025-06-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_no', models.CharField(max_length=20)),
                ('ward_no', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_contact', models.CharField(max_length=15)),
                ('availability', models.IntegerField(choices=[(1, 'Available'), (0, 'Not Available')], default=1)),
            ],
        ),
    ]
